import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {TreePine,BookOpen,Heart,Coins,Flag,Leaf,Play,Pause,FastForward,RotateCcw,Target,Swords,X,Volume2,VolumeX,Info,ArrowUp,Shield} from 'lucide-react';
import {TYPES,PADS,createGame,stats,upgradeCost,place,upgrade,sell,start,step} from './game';
import './style.css';

function Sprite({type,enemy=false}){return <span aria-hidden="true" className={`sprite sprite-${type} ${enemy?'enemy-art':''}`} style={{backgroundPosition:`${type*50}% ${enemy?'100%':'0%'}`}}/>;}
function App(){
 const game=useRef(createGame());const [,redraw]=useState(0);const [help,setHelp]=useState(false);const [muted,setMuted]=useState(true);const audio=useRef(null);const helpRef=useRef(null);const g=game.current;const refresh=()=>redraw(n=>n+1);
 const act=fn=>{fn(g);refresh();};
 useEffect(()=>{let id,last=performance.now(),paint=0;function tick(now){const state=game.current;const kills=state.kills;step(state,Math.min((now-last)/1000,.05));last=now;if(state.kills>kills&&audio.current){const ctx=audio.current;const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.connect(gain);gain.connect(ctx.destination);oscillator.frequency.setValueAtTime(620,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(260,ctx.currentTime+.08);gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.09);oscillator.start();oscillator.stop(ctx.currentTime+.1);}if(now-paint>32){refresh();paint=now;}id=requestAnimationFrame(tick);}id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[]);
 useEffect(()=>{const handler=e=>{if(help){if(e.key==='Escape')setHelp(false);return;}if(e.target.closest('button')&&e.code==='Space')return;if(['1','2','3'].includes(e.key)){g.building=Number(e.key)-1;g.selected=null;refresh();}if(e.code==='Space'){e.preventDefault();act(start);}if(e.key==='Escape'){g.selected=null;g.building=null;refresh();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[help,g]);
 useEffect(()=>{if(help)helpRef.current?.focus();},[help]);
 const selected=g.towers.find(t=>t.id===g.selected);const selectedStats=selected?stats(selected):null;
 const ended=g.status==='won'||g.status==='lost';
 const restart=()=>{game.current=createGame();refresh();};
 const sound=()=>{if(muted){const Context=window.AudioContext||window.webkitAudioContext;if(Context)audio.current=new Context();}else{audio.current?.close();audio.current=null;}setMuted(!muted);};
 const openHelp=()=>{if(g.status==='active')g.status='paused';setHelp(true);};
 return <><header className="topbar"><a className="brand" href="./"><TreePine/><div><strong>EMBERWOOD</strong><span>The last forest stands with you.</span></div></a><div className="header-actions"><button className="help-button" onClick={openHelp}><BookOpen size={18}/> How to play</button><button className="icon-button" aria-label={muted?'Enable sound':'Mute sound'} onClick={sound}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div></header>
 <main><div className="game-layout"><section className="battle-section"><div className="battle-heading"><div><h1>The woodland pass <Leaf/></h1><p>Build your defenses. Protect the heartwood.</p></div><div className="stats"><div><Heart className="heart"/><span>Lives<strong>{g.lives}<small> / 20</small></strong></span></div><div><Coins className="gold"/><span>Gold<strong className="gold">{g.gold}</strong></span></div><div><Flag className="sage"/><span>Wave<strong>{g.wave}<small> / 10</small></strong></span></div></div></div>
 <div className={`board ${g.building!==null?'building':''}`} aria-label="Woodland battlefield"><img className="terrain" src="/assets/forest.png" alt="A winding trail through a lush forest leading to the heartwood gate"/>
 <div className="map-label entrance">THE PASS <span>→</span></div><div className="board-tools"><button aria-label="Toggle game speed" onClick={()=>act(g=>g.speed=g.speed===1?2:1)}><FastForward size={14}/>{g.speed}×</button><button aria-label="Restart game" onClick={restart}><RotateCcw size={14}/></button></div>
 <svg className="effects" viewBox="0 0 1000 604" aria-hidden="true">{selected&&<circle cx={selected.x} cy={selected.y} r={selectedStats.range} fill="rgba(221,205,131,.10)" stroke="#efdf9b" strokeWidth="1.4" strokeDasharray="6 5"/>}{g.effects.map((e,i)=>e.reward?<text key={i} x={e.x} y={e.y-25-(.8-e.life)*30} fill="#ffe6a0" fontSize="17" textAnchor="middle">+{e.reward}</text>:<g key={i}><line x1={e.x} y1={e.y} x2={e.tx} y2={e.ty} stroke={TYPES[e.type].color} strokeWidth={e.type===1?5:2}/><circle cx={e.tx} cy={e.ty} r={e.type===1?24:7} fill={TYPES[e.type].color} opacity=".45"/></g>)}</svg>
 {PADS.map((p,i)=>{const t=g.towers.find(t=>t.pad===i);return <button key={i} className={`build-pad ${t?'occupied':''} ${t?.id===g.selected?'selected':''}`} style={{left:p[0]*100+'%',top:p[1]*100+'%'}} aria-label={t?`${TYPES[t.type].name} at clearing ${i+1}`:`Build at clearing ${i+1}`} onClick={()=>act(g=>place(g,i))}>{t?<><Sprite type={t.type}/><span className="tower-level">{'◆'.repeat(1+Math.max(t.damageLevel,t.rateLevel))}</span></>:<><span className="pad-ring"><Leaf/></span><span className="build-plus">+</span></>}</button>;})}
 {g.enemies.map(e=><div className={`enemy enemy-${e.type} ${e.slow?'frozen':''}`} key={e.id} style={{left:e.x/10+'%',top:e.y/604*100+'%'}}><span className="health"><i style={{width:e.hp/e.maxHp*100+'%'}}/></span><Sprite type={e.type} enemy/></div>)}
 {g.status==='paused'&&<div className="pause-overlay"><Pause size={32}/><h2>A moment of calm</h2><button className="primary" onClick={()=>act(start)}><Play size={16}/>Resume defense</button></div>}
 {ended&&<div className="end-overlay" role="dialog" aria-modal="true" aria-labelledby="end-title"><div><span className="end-icon">{g.status==='won'?<TreePine size={48}/>:<Shield size={48}/>}</span><p className="eyebrow">{g.status==='won'?'THE FOREST ENDURES':'THE PASS HAS FALLEN'}</p><h2 id="end-title">{g.status==='won'?'Victory, guardian.':'The heartwood is lost.'}</h2><p>{g.status==='won'?'You held the line through all 10 waves.':'Every great guardian begins again.'}</p><div className="end-stats"><span><strong>{g.wave}</strong>Waves reached</span><span><strong>{g.kills}</strong>Enemies defeated</span></div><button className="primary" onClick={restart}><RotateCcw size={17}/>Play again</button></div></div>}
 </div><div className="wave-bar"><div><Leaf/><span>{g.status==='ready'?(g.wave===0?'A quiet moment before the storm.':`Wave ${g.wave} cleared. The forest breathes again.`):g.status==='active'?`Wave ${g.wave} · ${g.total-g.spawned+g.enemies.length} enemies remaining`:g.status==='paused'?'The battle will wait for you.':g.status==='won'?'The heartwood is safe.':'A new defense awaits.'}</span></div><button className="primary" disabled={ended} onClick={()=>act(start)}>{g.status==='active'?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{g.status==='active'?'Pause':g.status==='paused'?'Resume':`Start wave ${Math.min(g.wave+1,10)}`}</button></div>
 <div className="wave-progress" aria-label={`Wave ${g.wave} of 10`}>{Array.from({length:10},(_,i)=><span className={i<g.wave?'filled':''} key={i}/>)}<span>HOLD THE LINE · 10 WAVES</span></div></section>
 <aside><div className="shop-heading"><Leaf/><h2>{selected?'Tower details':'Build a tower'}</h2>{selected&&<button className="close" aria-label="Close tower details" onClick={()=>act(g=>g.selected=null)}><X size={18}/></button>}</div><p className="aside-description">{selected?'Strengthen your defense. Hold your ground.':'Choose a tower, then place it in a clearing.'}</p>
 {selected?<div className="tower-detail"><div className="detail-hero"><Sprite type={selected.type}/><h3>{selectedStats.name}</h3><p>{selectedStats.description}</p></div><div className="detail-stats"><span><Swords size={15}/>Damage<strong>{selectedStats.damage}</strong></span><span><Target size={15}/>Range<strong>{(selectedStats.range/47).toFixed(1)}</strong></span><span><FastForward size={15}/>Shots/sec<strong>{selectedStats.rate.toFixed(2)}</strong></span></div>{['damage','rate'].map(kind=><button key={kind} className="upgrade" disabled={selected[kind+'Level']>=3||g.gold<upgradeCost(selected,kind)||ended} onClick={()=>act(g=>upgrade(g,kind))}><ArrowUp size={17}/><span><strong>{kind==='damage'?'Sharpen damage':'Faster fire rate'}</strong><small>Level {selected[kind+'Level']} / 3 · {kind==='damage'?'+50% base damage':'+35% base fire rate'}</small></span><b>{selected[kind+'Level']>=3?'MAX':`${upgradeCost(selected,kind)} G`}</b></button>)}<button className="sell" onClick={()=>act(sell)} disabled={ended}>Sell tower <span>+{Math.floor(selected.spent*.65)} gold</span></button><button className="back" onClick={()=>act(g=>{g.selected=null;g.building=0;})}>← Back to build menu</button></div>:<div className="tower-list">{TYPES.map((t,i)=><button key={t.name} className={`tower-card ${g.building===i?'chosen':''}`} disabled={ended} aria-pressed={g.building===i} onClick={()=>act(g=>{g.building=i;g.selected=null;g.message=`${t.name} selected. Choose an empty clearing (${t.cost} gold).`;})}><div className="tower-portrait"><Sprite type={i}/></div><div className="tower-copy"><div className="tower-title"><h3>{t.name}</h3><span><Coins size={15}/>{t.cost}</span></div><p>{t.description}</p><div className="tower-stats"><span><Target/> <span>Range<b>{(t.range/47).toFixed(1)}</b></span></span><span><Swords/><span>Damage<b>{t.damage}</b></span></span></div></div><span className="hotkey">{i+1}</span></button>)}</div>}
 <div className="tip"><Leaf/><div><h3>Make every shot count</h3><p>Cover the bends to keep enemies in range longer. Different towers work best together.</p></div></div><div className="kill-count"><Swords size={14}/><span>{g.kills} enemies defeated</span><span>+ gold per kill</span></div></aside></div>
 <footer><div aria-live="polite"><Info size={16}/>{g.message}</div><span><kbd>1</kbd>–<kbd>3</kbd> Towers <i>·</i> <kbd>Space</kbd> Start / pause</span></footer></main>
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();helpRef.current?.focus();}}}><button ref={helpRef} className="close" aria-label="Close instructions" onClick={()=>setHelp(false)}><X/></button><Leaf size={30}/><h2 id="help-title">The guardian’s field guide</h2><p>Protect the heartwood through 10 waves. Every enemy that reaches the gate costs a life. Lose all 20 and the forest falls.</p><ol><li><strong>Build your defense.</strong> Select a tower (keys 1–3), then choose a marked clearing. Your starting budget is 250 gold.</li><li><strong>Hold the line.</strong> Start a wave. Towers attack automatically; kills and completed waves earn gold.</li><li><strong>Grow stronger.</strong> Click a placed tower to upgrade damage and fire rate up to level 3, or sell it for 65% of your investment.</li><li><strong>Mix your towers.</strong> Rangers fire quickly, cannons hit groups, and frost slows targets. The final wave brings an elder ogre.</li></ol><p className="help-note">Space starts or pauses · Escape clears selection · 2× speeds up combat. Opening this guide pauses the battle.</p></section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
